### ISSUE TITLE
Add option to choose accent color

### ISSUE THREAD

**Issue by eurunuela** [executablebooks/myst-theme#227]
### Context

Currently, the themes use Tailwind's blue as the accent color with different tints and shades used throughout the themes.

### Proposal

To give users another customization option, the themes could have an `accent-color` option that would only accept Tailwind colors. The themes would then use this accent color, but wouldn't change the tint and shades to make it easier for devs to develop the feature.

### Tasks and updates

- [ ] Add `accent-color` option to config file.
- [ ] Read the user-given color in the different `jsx` files.
- [ ] Change all instances of `text-blue-600` and others to `text-{accentColor}-600`.

**Comment by agoose77** [comment]
Thanks for opening this! Although this is the first issue, it's a specific example of a general problem that we later opened an issue, so I'm going to close it as a duplicate of that.
